package com.example.cask.engine

/**
 * A curated, hand-tuned table of the corrections a statistical model can't make on its own, plus a
 * little common-sense language data for predictions. It exists because the shipped frequency list
 * (Norvig's `count_1w`, web-derived) contains thousands of *misspellings as high-frequency entries* —
 * `im` (37M), `dont` (20M), `cant`, `wont`, `teh`, `recieve`, `alot`, `definately`, … all look like
 * perfectly good words to a pure dictionary lookup. The noisy-channel model therefore never touches
 * them ("it's already a known word"), which is the single biggest reason naive autocorrect feels dumb.
 *
 * This table fixes the most common offenders directly and, crucially, **overrides dictionary
 * membership**: a [Fix] is applied even when the typed string is itself in the dictionary. Two tiers:
 *
 *  - [Fix.auto] `true`  — the typed form is essentially never intended (`dont`, `recieve`, `teh`); it
 *    is auto-applied at the word boundary (and still one-tap revertable).
 *  - [Fix.auto] `false` — ambiguous, because the typed form is also a common real word (`its`, `were`,
 *    `well`, `lets`, `id`); it is only *offered* at the top of the suggestion strip, never forced.
 *
 * Corrections carry their own canonical capitalization/punctuation (`I'm`, `don't`, `a lot`); the
 * engine re-cases them to match how the user typed (see `CorrectionEngine.recaseCurated`). Anything
 * the user reverts is remembered in [PersonalStore] and never re-applied.
 */
object CommonCorrections {

    /** A correction target. [to] is the canonical display form; [auto] gates auto-application. */
    data class Fix(val to: String, val auto: Boolean)

    private val map: HashMap<String, Fix> = HashMap(512)

    /** The correction for [typedLower] (already lowercased), or `null` if none is curated. */
    fun lookup(typedLower: String): Fix? = map[typedLower]

    fun isKnownCorrection(typedLower: String): Boolean = map.containsKey(typedLower)

    /** True if [typedLower] is a curated *auto* typo (e.g. `dont`, `im`) — never predict/suggest it. */
    fun isAutoTypo(typedLower: String): Boolean = map[typedLower]?.auto == true

    // ---- Table construction ------------------------------------------------

    private fun auto(to: String, vararg typed: String) { for (t in typed) map[t] = Fix(to, auto = true) }
    private fun suggest(to: String, vararg typed: String) { for (t in typed) map[t] = Fix(to, auto = false) }

    init {
        // -- Contractions typed without the apostrophe (unambiguous: not real words) --------------
        auto("I'm", "im")
        auto("I've", "ive")
        auto("you're", "youre")
        auto("you'll", "youll")
        auto("you've", "youve")
        auto("you'd", "youd")
        auto("don't", "dont")
        auto("doesn't", "doesnt", "dosnt")
        auto("didn't", "didnt")
        auto("isn't", "isnt")
        auto("aren't", "arent")
        auto("wasn't", "wasnt")
        auto("weren't", "werent")
        auto("won't", "wont")
        auto("can't", "cant")
        auto("couldn't", "couldnt")
        auto("wouldn't", "wouldnt")
        auto("shouldn't", "shouldnt")
        auto("haven't", "havent")
        auto("hasn't", "hasnt")
        auto("hadn't", "hadnt")
        auto("that's", "thats")
        auto("what's", "whats")
        auto("where's", "wheres")
        auto("who's", "whos")
        auto("how's", "hows")
        auto("there's", "theres")
        auto("here's", "heres")
        auto("they're", "theyre")
        auto("they'll", "theyll")
        auto("they've", "theyve")
        auto("they'd", "theyd")
        auto("we've", "weve")
        auto("she's", "shes")
        auto("he's", "hes")
        auto("should've", "shouldve")
        auto("would've", "wouldve")
        auto("could've", "couldve")
        auto("might've", "mightve")
        auto("must've", "mustve")
        auto("y'all", "yall")
        auto("o'clock", "oclock")
        auto("ma'am", "maam")
        // I-forms typed with apostrophe but lowercase i -> fix the capital
        auto("I'm", "i'm")
        auto("I've", "i've")
        auto("I'd", "i'd")
        auto("I'll", "i'll")

        // -- Ambiguous contractions (typed form is also a common real word) -> suggest only --------
        suggest("it's", "its")
        suggest("we're", "were")
        suggest("we'll", "well")
        suggest("I'll", "ill")
        suggest("I'd", "id")
        suggest("we'd", "wed")
        suggest("let's", "lets")
        suggest("he'll", "hell")
        suggest("she'll", "shell")

        // -- Common misspellings (not valid words; safe to auto-apply) -----------------------------
        auto("the", "teh", "hte", "thr", "tje")
        auto("and", "adn", "nad", "anbd", "annd")
        auto("this", "thsi", "tihs")
        auto("that", "taht")
        auto("you", "yuo", "yu")
        auto("with", "wiht", "wtih")
        auto("just", "jsut")
        auto("from", "fro")
        auto("have", "ahve", "haev")
        auto("they", "tehy")
        auto("there", "thre")
        auto("their", "thier")
        auto("would", "wuold", "owuld")
        auto("could", "cuold")
        auto("should", "shuold")
        auto("because", "becuase", "becasue", "becuse", "bcause")
        auto("which", "wich", "whcih")
        auto("receive", "recieve")
        auto("received", "recieved")
        auto("receiving", "recieving")
        auto("believe", "beleive", "belive")
        auto("believed", "beleived")
        auto("definitely", "definately", "definatly", "definitly", "defiantly")
        auto("definite", "definate")
        auto("separate", "seperate")
        auto("separated", "seperated")
        auto("separately", "seperately")
        auto("occurred", "occured")
        auto("occurring", "occuring")
        auto("occurrence", "occurance", "occurence")
        auto("until", "untill", "untl")
        auto("a lot", "alot")
        auto("friend", "freind")
        auto("friends", "freinds")
        auto("weird", "wierd")
        auto("achieve", "acheive")
        auto("achieved", "acheived")
        auto("across", "accross")
        auto("against", "agains", "agasint")
        auto("argument", "arguement")
        auto("beginning", "begining", "beginnig")
        auto("calendar", "calender")
        auto("careful", "carefull")
        auto("cemetery", "cemetary")
        auto("colleague", "collegue", "colleauge")
        auto("coming", "comming")
        auto("committed", "commited")
        auto("completely", "completly")
        auto("conscious", "concious")
        auto("disappoint", "dissapoint", "disapoint")
        auto("disappear", "dissapear", "disapear")
        auto("embarrass", "embarass", "embaras")
        auto("environment", "enviroment", "enviornment")
        auto("existence", "existance")
        auto("experience", "experiance")
        auto("familiar", "familar")
        auto("finally", "finaly")
        auto("foreign", "foriegn")
        auto("forty", "fourty")
        auto("government", "goverment", "govenment")
        auto("grammar", "grammer")
        auto("guard", "gaurd")
        auto("happened", "happend", "hapened")
        auto("harass", "harrass")
        auto("immediately", "immediatly", "imediately")
        auto("independent", "independant")
        auto("interesting", "intresting", "interseting")
        auto("knowledge", "knowlege", "knowledg")
        auto("leisure", "liesure")
        auto("maintenance", "maintainance", "maintenence")
        auto("millennium", "millenium")
        auto("necessary", "neccessary", "necesary", "neccesary")
        auto("noticeable", "noticable")
        auto("occasion", "occassion", "ocassion")
        auto("particular", "paticular")
        auto("performance", "perfomance")
        auto("persistent", "persistant")
        auto("possession", "posession", "possesion")
        auto("preceding", "preceeding")
        auto("privilege", "privelege", "priviledge")
        auto("probably", "probaly", "probally", "prolly", "probly")
        auto("pronunciation", "pronounciation")
        auto("publicly", "publically")
        auto("really", "realy", "rly")
        auto("recommend", "recomend", "reccomend", "reccommend")
        auto("referred", "refered")
        auto("relevant", "relevent")
        auto("religious", "religous")
        auto("remember", "remeber", "rember", "remmeber")
        auto("restaurant", "resturant", "restaraunt", "restarunt")
        auto("rhythm", "rythm", "rhythym")
        auto("secretary", "secratary")
        auto("seize", "sieze")
        auto("similar", "similiar", "simlar")
        auto("sincerely", "sincerly")
        auto("speech", "speach")
        auto("successful", "succesful", "successfull", "sucessful", "sucesful")
        auto("surprise", "suprise", "surprize")
        auto("tendency", "tendancy")
        auto("threshold", "threshhold")
        auto("tomorrow", "tommorow", "tomorow", "tommorrow", "tomorro")
        auto("truly", "truely")
        auto("unfortunately", "unfortunatly")
        auto("useful", "usefull")
        auto("usually", "usualy", "usualy", "usaully")
        auto("vacuum", "vaccum", "vacume")
        auto("whether", "wether")
        auto("wherever", "whereever")
        auto("writing", "writting")
        auto("written", "writen")
        auto("yacht", "yatch")
        auto("thanks", "thanx", "thnx", "thnks")
        auto("about", "abuot", "abotu")
        auto("people", "peopl", "poeple", "peolpe")
        auto("something", "somethign", "somthing", "someting")
        auto("everything", "everythign", "everthing")
        auto("through", "throught", "throuh")
        auto("first", "frist", "fisrt")
        auto("right", "rihgt")
        auto("little", "littel")
        auto("everyone", "everone")
        auto("always", "alwasy", "allways")
        auto("never", "nevr")
        auto("really", "realli")
        auto("going", "goign")
        auto("doing", "doign")
        auto("being", "beign")
        auto("makes", "amkes")
        auto("does", "deos")
        auto("good", "gud", "goood")
        auto("great", "graet")
        auto("night", "nite", "nigth")
        auto("morning", "mornign")
        auto("year", "yera")
        auto("your", "yoru")

        // -- More everyday misspellings (all non-words; safe to auto-apply) -------------------------
        auto("again", "agian", "agaian", "agan")
        auto("against", "agianst")
        auto("almost", "almsot", "alomst")
        auto("already", "alraedy", "alredy")
        auto("although", "althought", "altough")
        auto("amount", "ammount")
        auto("another", "antoher", "anothe")
        auto("answer", "anwser", "asnwer")
        auto("anyone", "anyoen")
        auto("anything", "anythign", "anyhting")
        auto("anyway", "anywa", "anway")
        auto("appreciate", "apreciate", "appreciatte")
        auto("around", "aroud", "arround")
        auto("awesome", "awsome", "aweosme")
        auto("available", "avaliable", "availble", "avilable")
        auto("basically", "basicly", "basicaly")
        auto("beautiful", "beatiful", "beutiful", "beautifull")
        auto("before", "beofre", "befor")
        auto("better", "bettter", "beter")
        auto("business", "buisness", "busness", "bussiness")
        auto("character", "charcter", "charecter")
        auto("clothes", "cloths", "clotes")
        auto("decision", "desicion", "decison")
        auto("different", "diffrent", "diferent", "differnt")
        auto("difference", "diffrence", "diference")
        auto("during", "durring", "duing")
        auto("easily", "easly", "easliy")
        auto("enough", "enought", "enuf", "enogh")
        auto("especially", "expecially", "especialy")
        auto("everybody", "everbody")
        auto("example", "exmaple", "exampel")
        auto("excited", "exicted", "exited")
        auto("favorite", "favorit", "favourit")
        auto("february", "febuary", "februry")
        auto("finally", "finallly")
        auto("guarantee", "garentee", "gaurantee", "garantee")
        auto("happen", "hapen")
        auto("important", "importnat", "imporant", "importent")
        auto("information", "inforamtion", "infromation")
        auto("instead", "insted", "intead")
        auto("interest", "intrest", "interset")
        auto("library", "libary", "librery")
        auto("listen", "lisen", "listne")
        auto("maybe", "mabye", "maybee")
        auto("message", "mesage", "messge")
        auto("minute", "minit", "minuet")
        auto("number", "nubmer", "numbr")
        auto("obviously", "obviosly", "obvisouly")
        auto("opportunity", "oppurtunity", "oportunity", "opurtunity")
        auto("perhaps", "perhasp", "prehaps")
        auto("please", "pleae", "plese", "pls", "plz", "pleeease")
        auto("question", "questin", "quesiton", "qustion")
        auto("quickly", "quikly", "quicky")
        auto("ridiculous", "rediculous", "ridiculus")
        auto("running", "runing", "runnning")
        auto("schedule", "schedual", "schedlue")
        auto("sentence", "sentance", "senetence")
        auto("seriously", "seriosly", "seriousy")
        auto("started", "strated", "statred")
        auto("strength", "strenght", "stregth")
        auto("studying", "studing", "studyng")
        auto("succeed", "suceed", "succede")
        auto("suggest", "sugest", "sugges")
        auto("themselves", "themselfs")
        auto("thought", "thaught", "thoght", "thouhgt")
        suggest("through", "thru") // "thru" is sometimes intentional — offer, don't force
        auto("together", "togeather", "togther", "togehter")
        auto("tongue", "tounge")
        auto("tonight", "tonite", "tonihgt")
        auto("understand", "undestand", "understnad")
        auto("welcome", "wlecome", "welcom", "welcme")
        auto("whole", "whoel")
        auto("woman", "womam")
        auto("women", "wemen")
        auto("wonderful", "wonderfull", "wondeful")
        auto("work", "wrok")
        auto("world", "wrold", "worl")
        auto("yourself", "youself", "yourselve")

        // -- More contractions typed without the apostrophe ----------------------------------------
        auto("what're", "whatre")
        auto("when's", "whens")
        auto("why's", "whys")
        auto("c'mon", "cmon")
        auto("everyone's", "everyones")
        suggest("there'll", "therell")

        // -- Additional everyday misspellings (all non-words; safe to auto-apply) -------------------
        auto("address", "adress", "addres")
        auto("apparent", "aparent", "apparant")
        auto("appearance", "apperance", "appearence")
        auto("benefit", "benifit")
        auto("category", "catagory")
        auto("challenge", "chalenge", "challange")
        auto("committee", "commitee", "comittee")
        auto("convenient", "conveniant", "convienient", "convinient")
        auto("criticism", "critisism")
        auto("curiosity", "curiousity")
        auto("desperate", "desparate")
        auto("development", "developement")
        auto("dilemma", "dilema")
        auto("discipline", "disipline", "dicipline")
        auto("efficient", "efficent", "efficiant")
        auto("eighth", "eigth")
        auto("embarrassing", "embarassing")
        auto("equipment", "equiptment")
        auto("exaggerate", "exagerate")
        auto("excellent", "excelent", "excellant")
        auto("exercise", "excercise", "exercize")
        auto("extreme", "extreem")
        auto("fascinating", "facinating")
        auto("forward", "foward")
        auto("generally", "generaly")
        auto("guidance", "guidence")
        auto("height", "heigth", "hieght")
        auto("ignorance", "ignorence")
        auto("immediate", "imediate")
        auto("intelligence", "inteligence", "intelligance")
        auto("interrupt", "interupt")
        auto("length", "lenght")
        auto("lonely", "lonley")
        auto("meant", "ment")
        auto("medicine", "medecine")
        auto("mischievous", "mischievious")
        auto("muscle", "muscel")
        auto("naturally", "naturaly")
        auto("ninety", "ninty")
        auto("occasionally", "occasionaly", "ocasionally", "occassionally")
        auto("official", "offical")
        auto("originally", "origionally", "orignally")
        auto("parallel", "parralel", "paralel")
        auto("permanent", "permenant", "permanant")
        auto("personally", "personaly")
        auto("physical", "phisical")
        auto("possible", "possable", "posible")
        auto("preferred", "prefered")
        auto("presence", "presance")
        auto("professional", "profesional", "proffesional")
        auto("professor", "profesor")
        auto("reference", "referance", "refrence")
        auto("relief", "releif")
        auto("resource", "resorce")
        auto("science", "sceince", "scince")
        auto("scissors", "scisors", "sissors")
        auto("several", "serveral")
        auto("significant", "signifigant", "significent")
        auto("special", "speical")
        auto("specific", "specfic", "spesific")
        auto("stomach", "stomache")
        auto("strategy", "stratagy")
        auto("sufficient", "sufficent", "suficient")
        auto("suspicious", "suspisious")
        auto("symptom", "symtom", "sympton")
        auto("technique", "techique", "tecnique")
        auto("temperature", "temperture", "tempreture")
        auto("terrible", "terible", "terrable")
        auto("thorough", "thourough")
        auto("transferred", "transfered")
        auto("twelfth", "twelth")
        auto("unnecessary", "unecessary", "unneccessary")
        auto("vegetable", "vegtable", "vegatable")
        auto("vehicle", "vehical", "vehicel")
        auto("version", "verison")
        auto("visible", "visable")
        auto("weight", "wieght", "wegiht")

        // -- High-frequency words mistyped via key transposition (guaranteed even with margins) ------
        auto("want", "wnat", "watn")
        auto("what", "waht")
        auto("when", "wehn", "whne")
        auto("then", "tehn", "hten")
        auto("them", "tehm")
        auto("time", "tiem", "itme")
        auto("like", "liek", "ilke")
        auto("love", "lvoe", "loev")
        auto("know", "knwo", "konw")
        auto("said", "siad")
        auto("make", "maek", "mkae")
        auto("made", "amde", "mdae")
        auto("more", "mroe", "omre")
        auto("much", "muhc")
        auto("need", "nede")
        auto("only", "olny", "onyl")
        auto("over", "ovre", "oevr")
        auto("same", "smae")
        auto("some", "soem")
        auto("sure", "srue", "suer")
        auto("take", "taek", "tkae")
        auto("thing", "thign", "hting")
        auto("think", "thikn", "htink")
        auto("very", "vrey", "veyr")
        auto("will", "wlil", "iwll")
        auto("word", "wrod")
        auto("back", "bakc")
        auto("both", "boht")
        auto("come", "ocme", "cmoe")
        auto("even", "evne")
        auto("find", "fnid", "fidn")
        auto("give", "gvie", "giev")
        auto("help", "hlep", "ehlp")
        auto("into", "itno", "inot")
        auto("look", "loko", "olok")
        auto("many", "mnay", "amny")
        auto("name", "naem", "nmae")
        auto("once", "ocne")
        auto("open", "opne")
        auto("read", "raed")
        auto("show", "shwo")
        auto("stop", "sotp")
        auto("wait", "wiat", "wati")
        auto("walk", "wakl")

        // -- Single-key slips of the very highest-frequency words (adjacent-key substitutions or a
        //    stray leading key). Every key here is a non-word, so the curated lookup fires
        //    unconditionally even where the statistical model is gun-shy. Includes the reported
        //    failures (yoi / yher). ---------------------------------------------------------------
        auto("you", "yoi")
        auto("your", "yoir", "yoru")
        auto("her", "yher")
        auto("young", "youbg", "yound")
        auto("the", "yhe", "rhe", "thw", "tge")
        auto("and", "amd", "anf", "abd", "qnd")
        auto("with", "wuth", "witg", "wirh", "wifh")
        auto("that", "thst", "thaz", "thaf")
        auto("this", "tjis", "thid", "thiz")
        auto("have", "havr", "habe", "havw")
        auto("they", "theu", "tjey", "thwy")
        auto("what", "whst", "wgat", "qhat")
        auto("when", "wgen", "qhen", "whrn", "wjen")
        auto("for", "fpr", "ofr")
        auto("not", "npt")
        auto("are", "arw", "qre", "aee")
        auto("was", "wss", "qas", "waz")
        auto("about", "abot", "aboit", "abour")
        auto("going", "goibg", "gokng", "goinf")
        auto("just", "juat", "juzt")
        auto("there", "thete", "thrre")
        auto("here", "hete", "herw", "heee")
        auto("from", "frpm", "ffom", "fron")
        auto("would", "woukd", "woudl", "wpuld")
        auto("people", "peopke", "peopel")
    }

    // ---- Curated prediction data (used when no learned context applies) ----------------------

    /** Good first words to predict at the start of a sentence (highest priority first). */
    val SENTENCE_STARTERS = listOf(
        "I", "The", "I'm", "It", "We", "You", "Thanks", "Hi", "Hey", "Yeah",
        "No", "Yes", "Okay", "What", "How", "Just", "Let", "Do", "Can", "That",
    )

    /** Generally useful next-word fillers when bigram/trigram data is unavailable (priority first). */
    val COMMON_NEXT = listOf(
        "the", "to", "a", "I", "you", "and", "is", "it", "that", "of",
        "for", "in", "on", "be", "have", "do", "we", "are", "this", "with",
        "not", "but", "so", "just", "can", "will", "was", "what", "out", "up",
    )

    /**
     * Lowercased set of words the predictor is allowed to surface even when they aren't dictionary
     * entries (e.g. `i'm`). Built from the curated prediction lists — never from the typo keys — so a
     * misspelling can never leak into predictions.
     */
    val PREDICTION_WHITELIST: Set<String> =
        (SENTENCE_STARTERS + COMMON_NEXT).mapTo(HashSet()) { it.lowercase() }
}
